# Define an ARG for the base image tag
ARG BASE_IMG_TAG=none

FROM pihole/pihole:${BASE_IMG_TAG} as openssl

WORKDIR /tmp/src

RUN set -e -x && \
    build_deps="build-base ca-certificates curl dirmngr gnupg libidn2-dev libssl-dev" && \
    apk add --update --no-cache $build_deps && \
    git clone https://github.com/openssl/openssl.git && \
    cd openssl && \
    ./config \
      --prefix=/opt/openssl \
      --openssldir=/opt/openssl \
      no-weak-ssl-ciphers \
      no-ssl3 \
      no-shared \
      -DOPENSSL_NO_HEARTBEATS \
      -fstack-protector-strong && \
    make depend && \
    nproc | xargs -I % make -j% && \
    make install_sw && \
    apk del --no-cache $build_deps && \
    rm -rf \
        /tmp/* \
        /var/tmp/* \
        /var/cache/apk/* \
        /var/lib/apk/lists/*


FROM pihole/pihole:${BASE_IMG_TAG} AS unbound

ENV NAME=unbound \
    UNBOUND_VERSION=latest \
    UNBOUND_DOWNLOAD_URL=https://nlnetlabs.nl/downloads/unbound/unbound-latest.tar.gz

WORKDIR /tmp/src

COPY --from=openssl /opt/openssl /opt/openssl

RUN build_deps="curl gcc musl-dev libevent-dev libexpat-dev libnghttp2-dev make flex bison" && \
    set -x && \
    apk add --update --no-cache $build_deps \
      bsdmainutils \
      ca-certificates \
      ldnsutils \
      libevent-2.1-7 \
      libexpat1 \
      libprotobuf-c-dev \
      protobuf-c-compiler && \
    curl -sSL $UNBOUND_DOWNLOAD_URL -o unbound.tar.gz && \
    tar xzf unbound.tar.gz && \
    rm -f unbound.tar.gz && \
    mv unbound-* unbound && \
    cd unbound && \
    groupadd _unbound && \
    useradd -g _unbound -s /dev/null -d /etc _unbound && \
    ./configure \
        --disable-dependency-tracking \
        --prefix=/opt/unbound \
        --with-pthreads \
        --with-username=_unbound \
        --with-ssl=/opt/openssl \
        --with-libevent \
        --with-libnghttp2 \
        --enable-dnstap \
        --enable-tfo-server \
        --enable-tfo-client \
        --enable-event-api \
        --enable-subnet && \
    make install && \
    mv /opt/unbound/etc/unbound/unbound.conf /opt/unbound/etc/unbound/unbound.conf.example && \
    apk del --no-cache $build_deps && \
    rm -rf \
        /opt/unbound/share/man \
        /tmp/* \
        /var/tmp/* \
        /var/cache/apk/* \
        /var/lib/apk/lists/*


FROM pihole/pihole:${BASE_IMG_TAG}

WORKDIR /tmp/src

COPY --from=unbound /opt /opt

RUN set -x && \
    apk add --update --no-cache \
      bsdmainutils \
      ca-certificates \
      ldnsutils \
      libevent-2.1-7 \
      libnghttp2-14 \
      libexpat1 \
      libprotobuf-c1 && \
    groupadd _unbound && \
    useradd -g _unbound -s /dev/null -d /etc _unbound && \
    apk del --no-cache $build_deps && \
    rm -rf \
        /opt/unbound/share/man \
        /tmp/* \
        /var/tmp/* \
        /var/cache/apk/* \
        /var/lib/apk/lists/*

WORKDIR /opt/unbound/

# copy extra files
COPY lighttpd-external.conf /etc/lighttpd/external.conf
COPY 99-edns.conf /etc/dnsmasq.d/99-edns.conf
COPY data/ /
RUN chmod +x /unbound.sh

# set version label
LABEL maintainer="OrigamiOfficial"

# environment settings
ENV PIHOLE_DNS_ 127.0.0.1#5335
ENV PATH /opt/unbound/sbin:"$PATH"

# target run
CMD ["/unbound.sh"]